[package]
authors = ["Jason Ozias <jason.ozias@gmail.com>"]
name = "mung"
version = "0.1.0"

[dependencies]
clap = "2.6.0"
lazy_static = "0.2.1"
regex = "0.1.71"

[dependencies.clippy]
optional = true
version = "0.0.76"

[features]
lint = ["clippy"]
